# Generated by Django 4.1.3 on 2023-01-12 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verificationotp_refreshtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='First Name'),
        ),
    ]
