# Generated by Django 4.1.3 on 2023-01-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelTable(
            name='goal',
            table='goal',
        ),
    ]
