# Generated by Django 4.1.3 on 2023-01-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_goal_options_alter_goal_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.PositiveIntegerField(verbose_name='Goal'),
        ),
    ]
